[WIP] main thread blockされたときにメモリー使用量急に増えないようにした
huiping192/Kitsunebi pull request #3
Opened 2022-02-08 07:41 UTC by huiping192

2022-02-08 07:41 UTC, huiping192 commented on Sources/Kitsunebi/AnimationView.swift
> +          guard let frame = frameBlock() else { return }
main thread使用後にframe取得するように変更

2022-02-09 14:13 UTC, noppefoxwolf requested changes

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> +    DispatchQueue.main.async { [weak self] in
ここはどうしてメインスレッドになったんですか？

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> +    DispatchQueue.main.async { [weak self] in
ここもどうしてメインスレッドになったのか知りたいです。

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> +  internal func didOutput() {
didOutputだけだと何が？となってしまうので名前を変えたいです。

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> -      self?.gpuLayer.drawableSize = frame.size
この行を消したのはどうしてですか？

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> +          guard let frame = self.engineInstance?.fetchCurrentFrame() else { return }
これまでrenderThreadで実行されていたframeの取り出しがrenderQueueで行われるようになっていますが問題ないですか？

2022-02-09 14:13 UTC, noppefoxwolf commented on Sources/Kitsunebi/VideoEngine.swift
> +      self?.readQueue.async { [weak self] in
renderThreadからキューの移動が起こってしまっているのでパフォーマンス的に良くないかもしれないです

2022-02-10 07:58 UTC, huiping192 commented on Sources/Kitsunebi/AnimationView.swift
> -      self?.gpuLayer.drawableSize = frame.size
frame取得があとで行うようになったので、ここでサイズ指定ができなくなりました。
動画サイズフレームごとに変動する可能性少ないので、playのタイミングでサイズ指定するようにしました。

2022-02-10 07:58 UTC, huiping192 commented on Sources/Kitsunebi/AnimationView.swift
> +    DispatchQueue.main.async { [weak self] in
playを呼ばれてるのはmain threadとは限らないので、gpuLayerの操作にmain threadが必要で、ここだけmain threadで実行するようにした

2022-02-10 07:59 UTC, huiping192 commented on Sources/Kitsunebi/AnimationView.swift
> +    DispatchQueue.main.async { [weak self] in
上と同じ理由です

2022-02-10 08:03 UTC, huiping192 commented on Sources/Kitsunebi/AnimationView.swift
> +          guard let frame = self.engineInstance?.fetchCurrentFrame() else { return }
fetchCurrentFrame内部的にreadqueueで取得しています。
そしてframe取り出しも状態一致するため、renderThreadからreadqueueに変更しました

2022-02-10 08:04 UTC, huiping192 commented on Sources/Kitsunebi/VideoEngine.swift
> +      self?.readQueue.async { [weak self] in
renderThread使えるかどうか最初と思ったが、 objc のperform使うしかなく、これ使うとしても返り値取れないので、
threadの使用やめてdispatchqueueに変更しました


https://developer.apple.com/documentation/objectivec/nsobject/1414476-perform

2022-02-10 09:02 UTC, noppefoxwolf approved these changes

2022-02-10 09:02 UTC, noppefoxwolf commented on Sources/Kitsunebi/AnimationView.swift
> +    DispatchQueue.main.async { [weak self] in
メインスレッドのキューに追加する必要は多分ないので次の対応でお願いします。

1. メソッドの先頭に
```
guard Thread.isMainThread else { preconditionFailure() }
```

2. @MainActorを追加

2022-02-10 09:02 UTC, noppefoxwolf commented on Sources/Kitsunebi/VideoEngine.swift
> +  func didFrameUpdated()
`didFrameUpdated`ということは、メソッド名からはcurrentFrameIndexが+1されていることを期待しますがそうなってない気がします。

2022-02-10 09:03 UTC, noppefoxwolf commented
良さそうです、CALayerってメインスレッド以外から呼べるんですね（スレッドサニタイザーとかに怒られない…？）

2022-02-10 09:33 UTC, huiping192 commented
self.layerだと怒りますね。多分UIView内部でチェックしてると思われます。 

layer.nextDrawable() とsize設定自体は大丈夫でした

2022-02-10 13:38 UTC, huiping192 commented
drawableをrenderqueueで取得とコメント追加しました.

clear methodもmain thread使ってるのでそこも修正

2022-02-14 03:39 UTC, noppefoxwolf approved these changes

2022-02-15 04:00 UTC, merged